"""sync models with db

Revision ID: 7901bce79748
Revises: 
Create Date: 2025-06-12 08:23:33.723855

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7901bce79748'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('global_stats')
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.alter_column('difficulty',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'Facile'"))
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'active'"))

    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calories_burned', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gps_data', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('weather_conditions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.alter_column('distance',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.drop_column('route_data')
        batch_op.drop_column('calories')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calories', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('route_data', mysql.TEXT(), nullable=True))
        batch_op.alter_column('distance',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.drop_column('notes')
        batch_op.drop_column('weather_conditions')
        batch_op.drop_column('gps_data')
        batch_op.drop_column('calories_burned')

    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'active'"))
        batch_op.alter_column('difficulty',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'Facile'"))

    op.create_table('global_stats',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('total_users', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('active_users', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('total_runs', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('total_distance', mysql.FLOAT(), nullable=False),
    sa.Column('average_pace', mysql.FLOAT(), nullable=False),
    sa.Column('runs_this_month', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('distance_this_month', mysql.FLOAT(), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
